const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

const generateInvoicePDF = async (booking, user) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const filePath = path.join(
        __dirname,
        `../temp/invoice_${booking._id}.pdf`
      );
      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      // ===== HEADER =====
      const logoUrl =
        "https://res.cloudinary.com/dwxsprktq/image/upload/v1728119205/packers_logo.png";
      doc.image(logoUrl, 50, 30, { width: 80 });
      doc
        .fontSize(20)
        .text("Smart Packers & Movers", 150, 40)
        .fontSize(10)
        .fillColor("gray")
        .text("Email: support@smartpackers.com", 150, 60)
        .text("Phone: +91 98765 43210", 150, 75);

      doc.moveTo(50, 100).lineTo(550, 100).stroke();
      doc.moveDown(2);

      // ===== INVOICE TITLE =====
      doc
        .fontSize(16)
        .fillColor("black")
        .text("BOOKING INVOICE", 50, 120, { align: "center" })
        .moveDown(1);

      // ===== CUSTOMER DETAILS =====
      doc.fontSize(12).text("Customer Details:", 50, 160, { bold: true });
      doc.fontSize(10);
      doc.text(`Name: ${user.name}`, 50, 180);
      doc.text(`Email: ${user.email}`, 50, 195);
      doc.text(`Phone: ${user.phone}`, 50, 210);
      doc.text(
        `Address: ${
          user.address?.street
            ? `${user.address.street}, ${user.address.city}, ${user.address.state}`
            : "N/A"
        }`,
        50,
        225,
        { width: 500 }
      );

      // ===== BOOKING DETAILS =====
      doc.moveDown(2);
      doc.fontSize(12).text("Booking Details:", 50, 270);
      doc.fontSize(10);
      doc.text(`Booking ID: ${booking._id}`, 50, 290);
      doc.text(`Service Type: ${booking.serviceType || "General"}`, 50, 305);
      doc.text(`Status: ${booking.status}`, 50, 320);
      doc.text(`Payment Status: ${booking.paymentStatus || "Pending"}`, 50, 335);
      doc.text(`Booking Date: ${booking.createdAt.toLocaleString()}`, 50, 350);

      // ===== PAYMENT DETAILS =====
      doc.moveDown(2);
      doc.fontSize(12).text("Payment Summary:", 50, 380);
      doc.fontSize(10);
      const basePrice = booking.totalAmount || 0;
      doc.text(`Base Price: ₹${basePrice}`, 50, 400);
      const gst = (basePrice * 0.18).toFixed(2);
      doc.text(`GST (18%): ₹${gst}`, 50, 415);
      const total = (basePrice * 1.18).toFixed(2);
      doc.fontSize(12).text(`Total Payable: ₹${total}`, 50, 440, { bold: true });

      // ===== FOOTER =====
      doc.moveDown(4);
      doc
        .fontSize(10)
        .fillColor("gray")
        .text(
          "Thank you for choosing Smart Packers & Movers. Have a safe moving experience!",
          50,
          500,
          { width: 500, align: "center" }
        );

      doc.moveTo(50, 550).lineTo(550, 550).stroke();
      doc
        .fontSize(9)
        .fillColor("gray")
        .text("Generated by Smart Packers & Movers © 2025", 50, 560, {
          align: "center",
        });

      doc.end();

      stream.on("finish", () => resolve(filePath));
    } catch (err) {
      reject(err);
    }
  });
};

module.exports = generateInvoicePDF;
